import type { Config } from 'tailwindcss';
import tailwindcssAnimate from 'tailwindcss-animate';

export default {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        backgroundSecondary: 'hsl(var(--background-secondary))',
        backgroundTertiary: 'hsl(var(--background-tertiary))',
        backgroundQuaternary: 'hsl(var(--background-quaternary))',
        border: 'hsl(var(--border))',
        mutedText: 'var(--muted-text)',
        linkColor: 'var(--link-color)',
        highlight: 'var(--highlight)',
        textPrimary: 'var(--text-primary)',
        textSecondary: 'var(--text-secondary)',
        textMuted: 'var(--text-muted)',
        textError: 'var(--text-error)',
        textSuccess: 'var(--text-success)',
        textWarning: 'var(--text-warning)',
        textInfo: 'var(--text-info)',
        cardBg: 'var(--card)',
        cardBorder: 'var(--card-border)',
        cardShadow: 'var(--card-shadow)',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        tertiary: 'var(--tertiary)',
        statusDanger: 'var(--status-danger)',
        statusWarning: 'var(--status-warning)',
        statusSuccess: 'var(--status-success)',
        statusInfo: 'var(--status-info)',
        priorityLow: 'var(--priority-low)',
        priorityMedium: 'var(--priority-medium)',
        priorityHigh: 'var(--priority-high)',
        priorityUrgent: 'var(--priority-urgent)',
        statusTodo: 'var(--status-todo)',
        statusInProgress: 'var(--status-inprogress)',
        statusDone: 'var(--status-done)',
        statusBlocked: 'var(--status-blocked)',
        buttonBg: 'var(--button-bg)',
        buttonHover: 'var(--button-hover)',
        buttonText: 'var(--button-text)',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
